clone_folder: c:\xaxlib
version: 2.15.{build}

build_script:
- ps: dotnet restore --verbosity quiet
- ps: msbuild YAXLib.2015.Core.sln /verbosity:minimal /t:rebuild /p:configuration=release
- ps: nuget restore YAXLib.2015.sln -verbosity quiet
- ps: msbuild YAXLib.2015.sln /verbosity:minimal /t:rebuild /p:configuration=release

test_script:
  - dotnet test YAXLibTests
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:"\"c:\xaxlib\YAXLibTests\bin\Release\YAXLibTests.dll\" --result=myresults.xml;format=AppVeyor"  -returntargetcode -filter:"+[YAXLib]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
